name: Deploy to Render

on:
  push:
    branches:
      - main  # or master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Ensure this matches your runtime

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests (Optional)
      - name: Run tests
        run: |
          echo "Running tests..."
          # Uncomment the next line if you have tests
          # pytest

      # 5. Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_URL }}"